<Project Sdk="Microsoft.NET.Sdk.Razor">
  <ItemGroup>
    <PackageReference Include="TimeZoneConverter" Version="7.2.0" />
    <PackageReference Include="Xunit.SkippableFact" Version="1.5.85" />
  </ItemGroup>
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.Globalization.UseNls" Value="true" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\BlazorLocalTime\BlazorLocalTime.csproj" />
    <ProjectReference Include="..\BlazorLocalTimeTest\BlazorLocalTimeTest.csproj" />
  </ItemGroup>
</Project>
